### ISSUE TITLE
Are unit tester 12.2.1 and 12.2.0 identical?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem-unittest#10]
It's was finding by accident and I am curious about it.
I first cloned your repo and change its version to 12.2.1 by the following codes.
```
git clone https://github.com/geoschem/geos-chem-unittest.git UT
cd UT
git checkout 12.2.1
```
Then I used `git log --tags --simplify-by-decoration --pretty="format:%ci %d"` to find the version is exactly 12.2.1. Except this long command, do you have any other convenient ways showing the UT and/or GC.Code that is being used?
```
2019-02-26 12:18:18 -0500  (HEAD, tag: 12.2.1)
```
However, when I check the contents of `./perl/CopyRunDirs.input` I found the following.
```
# %%% ID tags %%%
#
   VERSION        : 12.2.0
   DESCRIPTION    : Create run directory from UnitTest
```
Hence comes the question, which version do I use now? Or they are totally the same because Z in X.Y.Z just denotes some bug fixes and does not break the compatibility? For Code.GC and UT, could I only need to confirm that X and Y in X.Y.Z the same?

**Comment by lizziel** [comment]
Could you clarify what versions you are a using. The issue title specifies 12.2.1 and 12.2.0 but the content of your issue specifies 12.1.1 and 12.1.0. 

Regardless, I think the issue you mention applies to both. I looked at 12.2.1 and 12.1.1, and in both cases the CopyRunDirs.input file contains a hard-coded version string 12.2.0 and 12.1.0 respectively. I believe this is a mistake and the hard-coded numbers were accidentally not updated for the release. This will have no impact on checking out the correct code, and these versions the string is not used for anything. The CopyRunDirs.input file is meant to be edited prior to using, so you can edit those numbers or even remove the line.

Regarding how to conveniently show version, you can simply use 'git log' at the command prompt and avoid the additional flags you listed. 'git log' will list all commits with the most recent commit first, and it will also display the tag name, if any. For the GEOS-Chem unit tester all official versions are tagged so you can tell the official version number from that display. The tag is independent from the hard-coded string in CopyRunDirs.input and can be trusted.

Another option is to use gitk, a GUI that usually comes with git installs. It shows the history of commits along with tags, so you can use this to quickly scan the changes between versions and hone in on specific file changes. In some cases the Y and Z versions of the unit tester are the same. For 12.1.0 and 12.1.1 there was one commit difference, as seen using gitk shown in this screenshot:
<img width="893" alt="gitk" src="https://user-images.githubusercontent.com/651947/65436953-f2fbf980-ddf0-11e9-8eff-4efbffe028cf.png">

The one commit difference is also visible using 'git log' but additional commands are needed to see the file diffs. The 'git log' output is shown here:
<img width="759" alt="git_log" src="https://user-images.githubusercontent.com/651947/65436957-f5f6ea00-ddf0-11e9-86a9-eef248ee1d74.png">

If you are interested in 12.2.0 and 12.2.1, you can do the same procedure to investigate the differences there. Always rely on the git info for version information rather than the hard-coded string in CopyRunDirs.input.

**Comment by FeiYao-Edinburgh** [comment]
> Always rely on the git info for version information rather than the hard-coded string in CopyRunDirs.input.

Thanks! This is helpful.

**Comment by FeiYao-Edinburgh** [comment]
> 'git log' will list all commits with the most recent commit first, and it will also display the tag name, if any.

Maybe this is an issue of software, I run `git log` within Git Bash on a Linux server and I did not see any tag information...

![image](https://user-images.githubusercontent.com/43779303/69232322-c0694580-0b82-11ea-9893-7b89506e22dc.png)

Anyway [`git log --tags --simplify-by-decoration --pretty="format:%ci %d"`](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/research-workflow.html#get-source-code-and-checkout-model-version) works fine

![image](https://user-images.githubusercontent.com/43779303/69232394-e393f500-0b82-11ea-90fd-c3defcc4f96c.png)

**Comment by yantosca** [comment]
Thanks for writing.  I think it depends on your version of Git.  If you are using one of the more recent releases of Git, then the tags are indeed highlighted in the git log and git log--oneline commands.

```
> git --version
2.17.0
> git log --oneline -10
f9cf6245 (HEAD -> dev/12.7.0, origin/dev/12.7.0) Remove dry-run log file; all dry-run output now goes to stdout
9e2b9fb1 Now implement a HEMCO standalone dry-run
ca5ee233 For dryrun simulations, restore output to stdout and HEMCO log
b2530773 Update the formatting of the GEOS-Chem dry-run warning message
4e9eed36 Now use a simpler format for the dry-run output
50c2ef4a Merge branch 'master' into dev/12.7.0
0f510a9e Also write out simulation name to the HEMCO dry-run log file
320287e0 Fix a few outstanding issues for the dry-run output
3e0b07cb (tag: 12.6.2, origin/master, origin/HEAD, master) Update version to 12.6.2
6290ca95 Add modifications for printing out volcano emisisons in dry-runs
```
