### ISSUE TITLE
OFFLINE_BIOGENICVOC and MEGAN

### ISSUE THREAD

**Issue by barronh** [geoschem/geos-chem-unittest#23]
I noticed that the HEMCO_Config.template.standard has both the OFFLINE_BIOGENICVOC emissions enabled (true) and the MEGAN extension enabled (on).  The OFFLINE DUST, SEASALT, and SOILNOX are also enabled (true), but their corresponding extensions are disabled.

If I understand the behavior correctly, this could easily lead to double counting in "standard" simulations.

See lines 107 and 145 of

https://github.com/geoschem/geos-chem-unittest/blob/master/runs/shared_inputs/fullchem/HEMCO_Config.template.standard

**Comment by msulprizio** [comment]
Thanks for bringing this up. These settings are intentional. When methanol was added as an advected species in 12.7.0, we needed to include biogenic methanol emissions; however, the offline biogenic VOC emissions did not save out methanol. In order to properly account for those emissions, we needed to turn on the MEGAN extension. Code was added to hcox_megan_mod.F90 to check if offline biogenic VOC emissions are turned on, and if so to use the offline biogenic VOC emissions for species that are included in the offline biogenic VOC files. See commit https://github.com/geoschem/geos-chem/commit/3e2a48f06cd6b5533fa12a7f5a351c7684347baa in the GEOS-Chem repository for more details.

**Comment by barronh** [comment]
Thanks for the clarification. I was setting up a run with standard options, but wanted to run with on-line MEGAN instead of OFFLINE. The comments led me to expect that the two were in conflict. It might be worth adding a note.

```
# ----- OFFLINE EMISSIONS -------------------
# To use online emissions instead set the
# offline emissions to 'false' and the
# corresponding HEMCO extension to 'on':
#   OFFLINE_DUST        - DustDead or DustGinoux
#   OFFLINE_BIOGENICVOC - MEGAN
#   OFFLINE_SEASALT     - SeaSalt
#   OFFLINE_SOILNOX     - SoilNOx
#--------------------------------------------
```

**Comment by msulprizio** [comment]
We also realized this source of confusion and modified the comments in the dev/12.9.0 branch. When that version is released, the comment will read:

```
# ----- OFFLINE EMISSIONS -------------------
# To use online emissions instead set the
# offline emissions to 'false' and the
# corresponding HEMCO extension to 'on':
#   OFFLINE_DUST        - DustDead or DustGinoux
#   OFFLINE_BIOGENICVOC - MEGAN
#    - Note: MEGAN must always be on for certain
#            species not in OFFLINE_BIOGENICVOC
#   OFFLINE_SEASALT     - SeaSalt
#   OFFLINE_SOILNOX     - SoilNOx
#--------------------------------------------
```

**Comment by barronh** [comment]
Thank you!
